import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Google Font
import "./globals.css";
import NavBar from "@/components/Shared/NavBar";
import Footer from "@/components/Shared/Footer";



// Initialize Inter font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="betterTrip">
      <body className={inter.className}>
       <NavBar/>
       
        {children} {/* Render children */}
        <Footer/>
      </body>
    </html>
  );
}
